### ISSUE TITLE
Adding Input and Output Dcc components

### ISSUE THREAD

**Issue by kswain1** [plotly/dash-vanguard-report#3]
When I add input and output Dcc components to the report script. I am getting the new input component doesn't have a children component? I don't understand what they mean. 

- Maybe another way to ask this questions is do I make the script input and output callbacks to this script? 

Error Response: 
<img width="739" alt="screen shot 2018-06-25 at 6 45 25 pm" src="https://user-images.githubusercontent.com/9138420/41881232-032e5b5e-78a8-11e8-838a-f53414079a20.png">

Added Code to Page layout: 

<img width="741" alt="screen shot 2018-06-25 at 6 48 31 pm" src="https://user-images.githubusercontent.com/9138420/41881301-7182bbd6-78a8-11e8-8daf-e6b99618da66.png">

Added Code: 
<img width="668" alt="screen shot 2018-06-25 at 6 46 26 pm" src="https://user-images.githubusercontent.com/9138420/41881249-1f9f02ca-78a8-11e8-9aee-a5d74dd88845.png">

**Comment by bcdunbar** [comment]
@kswain1 This isn't an issue but a question. In the future, please post questions on the [community forum](https://community.plot.ly/). Thanks.

Your component_id for input and output are the same. See 'Dash App Layout' example here https://dash.plot.ly/getting-started-part-2

**Comment by kswain1** [comment]
I don't understand the app layout setup, and how to add new Output component that works with callbacks with your setup. I can pay a small fee for the feature add. (www.codementor.io) Yes, I am fairly new to the dash workflow.
