### ISSUE TITLE
Demo needs an update

### ISSUE THREAD

**Issue by Nemecsek** [plotly/dash-vanguard-report#5]
Doesn't work anymore with dash 0.22.0 and plotly 3.1.0
Would it be possible to update it? 
Alas my knowledge is very limited (that's why your demo is so important) and I cannot find the problems myself...

**Comment by bcdunbar** [comment]
@Nemecsek thanks for reporting. I'll look to update this over the next day or two.

In the interim, please note that this was built with (as noted in https://github.com/plotly/dash-vanguard-report/blob/master/requirements.txt):

dash==0.21.0
dash-core-components==0.20.2
dash-html-components==0.9.0
dash-renderer==0.11.3
plotly==2.4.1
